repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: detect-private-key

# Python hooks
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: \.py$

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        files: \.py$

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        files: \.py$
        additional_dependencies: [flake8-docstrings]

# JavaScript/TypeScript hooks
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.40.0
    hooks:
    -   id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
        -   eslint@8.40.0
        -   eslint-plugin-react@7.32.2
        -   eslint-plugin-react-hooks@4.6.0
        -   eslint-config-prettier@8.8.0
        -   eslint-plugin-prettier@4.2.1
        -   "@typescript-eslint/eslint-plugin@5.59.5"
        -   "@typescript-eslint/parser@5.59.5"
        -   prettier@2.8.8

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.8.8
    hooks:
    -   id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|yml|yaml|md)$
        exclude: '^(server/)'

# Security hooks
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks
